mybatis:
  mapper-locations: classpath:com/zzc/luntan/demo1/mapper/*.xml

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/luntan?serverTimezone=GMT%2B8
    username: root
    password: 687211
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

server:
  port: 8090
